# Writes OUTPUT_FILE with a hash of the sources that translate shaders (the recompiler and the
# program cache), so the shader disk cache survives rebuilds that don't change translation.
# The file is only rewritten when the hash changes, so unrelated rebuilds recompile nothing.

file(GLOB_RECURSE shader_sources
	"${SOURCE_DIR}/graphics/shader/*.cpp"
	"${SOURCE_DIR}/graphics/shader/*.h"
	"${SOURCE_DIR}/graphics/shader/*.inc"
	"${SOURCE_DIR}/graphics/host_gpu/renderer/pipeline/pipelineCache.cpp"
	"${SOURCE_DIR}/graphics/host_gpu/renderer/pipeline/pipelineCache.h"
	"${SOURCE_DIR}/graphics/host_gpu/renderer/pipeline/shaderDiskCache.cpp"
	"${SOURCE_DIR}/graphics/host_gpu/renderer/pipeline/shaderDiskCache.h"
)
list(SORT shader_sources)

set(combined "")
foreach(source IN LISTS shader_sources)
	file(RELATIVE_PATH relative "${SOURCE_DIR}" "${source}")
	file(SHA256 "${source}" digest)
	string(APPEND combined "${relative}:${digest}\n")
endforeach()
string(SHA256 hash "${combined}")

set(content "// Generated by generate_shader_hash.cmake; do not edit.\n#pragma once\n#define KYTY_SHADER_TRANSLATION_HASH \"${hash}\"\n")
if(EXISTS "${OUTPUT_FILE}")
	file(READ "${OUTPUT_FILE}" existing)
else()
	set(existing "")
endif()
if(NOT existing STREQUAL content)
	file(WRITE "${OUTPUT_FILE}" "${content}")
endif()
